# Generated by Django 5.0.7 on 2024-07-21 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manager_id', models.PositiveIntegerField()),
                ('province', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscalCode', models.CharField(max_length=16, unique=True)),
                ('type', models.CharField(choices=[('trainer', 'trainer'), ('nutritionist', 'nutritionist'), ('mixed', 'mixed')], max_length=50)),
                ('hiring_date', models.DateField(verbose_name='Hiring Date')),
                ('end_contract_date', models.DateField(null=True, verbose_name='End Contract Date')),
                ('attachments_uuid', models.CharField(max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('salary', 'salary'), ('tax', 'tax'), ('single', 'single')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.IntegerField(help_text='Frequency in months', null=True)),
                ('center_uuid', models.CharField(max_length=36)),
                ('employee_uuid', models.CharField(max_length=36, null=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('expiration_date', models.DateField(null=True, verbose_name='Expiratoin Date')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user_id', models.CharField()),
                ('center_uuid', models.CharField(max_length=36)),
                ('exec_time', models.DateTimeField()),
            ],
        ),
    ]
