# Generated by Django 5.0.7 on 2024-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0002_center_is_active_employee_is_active_exit_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='manager_id',
            field=models.CharField(),
        ),
    ]
