# Generated by Django 5.0.7 on 2024-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0004_employee_center_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_uuid',
            field=models.CharField(default='7ca984db-38bb-47c1-8865-f13e385dd58a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exit',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Expiration Date'),
        ),
    ]
