# Generated by Django 5.0.7 on 2024-07-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0006_alter_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_uuid',
        ),
        migrations.AlterField(
            model_name='review',
            name='exec_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.CharField(null=True),
        ),
    ]
