# Generated by Django 5.0.7 on 2024-07-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0007_remove_employee_user_uuid_alter_review_exec_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.CharField(),
        ),
    ]
