# Generated by Django 5.0.7 on 2024-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0008_alter_review_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='prova@defualt.it', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='fiscalCode',
            field=models.CharField(max_length=16),
        ),
    ]
