# Generated by Django 5.0.7 on 2024-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0009_employee_email_alter_employee_fiscalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
