# Generated by Django 5.0.7 on 2024-07-30 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0010_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBusyTrace',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_uuid', models.CharField(max_length=255)),
                ('prenotation_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prenotation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('employee_uuid', models.CharField(max_length=255)),
                ('center_uuid', models.CharField(max_length=255)),
                ('exec_time', models.DateTimeField(auto_now_add=True)),
                ('from_hour', models.DateTimeField()),
                ('to_hour', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('trainer', 'trainer'), ('nutritionist', 'nutritionist')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='hour_nutritionist_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='hour_trainer_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='center_uuid',
            field=models.CharField(max_length=255),
        ),
    ]
