# Generated by Django 5.0.7 on 2024-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0011_employeebusytrace_prenotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebusytrace',
            name='prenotation_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='prenotation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('to cancel', 'to cancel'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=10),
        ),
    ]
