# Generated by Django 5.0.7 on 2024-08-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0012_alter_employeebusytrace_prenotation_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeBusyTrace',
        ),
    ]
