# Generated by Django 5.0.7 on 2024-08-01 10:39

import gdstorage.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0013_delete_employeebusytrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('filetype', models.CharField(blank=True, max_length=10)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('attachment', 'attachment'), ('training', 'training'), ('diet', 'diet'), ('other', 'other')], max_length=10)),
                ('filedata', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='documents/')),
            ],
        ),
    ]
