# Generated by Django 5.0.7 on 2024-08-01 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerHandling', '0014_customercredit_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('user_email', models.EmailField(max_length=254)),
                ('card_number', models.CharField()),
                ('card_holder', models.CharField()),
                ('card_cvc', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('to cancel', 'to cancel'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('card_uuid', models.CharField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('to cancel', 'to cancel'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=10)),
            ],
        ),
    ]
