# Generated by Django 5.0.6 on 2024-07-20 16:47

import django.db.models.deletion
import gdstorage.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('filetype', models.CharField(blank=True, max_length=10)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
                ('filedata', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='imageProfile/')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('data_iscrizione', models.DateField(auto_now_add=True, verbose_name='data iscrizione')),
                ('is_superuser', models.BooleanField(default=False)),
                ('p_iva', models.CharField(max_length=11, null=True, unique=True)),
                ('groups', models.ManyToManyField(related_name='user_accounts', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('photo', models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
