# Generated by Django 5.0.6 on 2024-07-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='uuid',
            new_name='id',
        ),
    ]
