# Generated by Django 5.0.6 on 2024-07-25 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_uuid_useraccount_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invito',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_code', models.CharField(max_length=16)),
                ('employee_uuid', models.CharField(max_length=36)),
                ('exec_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied'), ('error', 'error')], max_length=10)),
            ],
        ),
    ]
