# Generated by Django 5.0.6 on 2024-07-16 09:51

import django.db.models.deletion
import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_photo_alter_useraccount_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('filetype', models.CharField(blank=True, max_length=10)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
                ('filedata', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='imageProfile/')),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.OneToOneField(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='users.photo'),
        ),
    ]
