# Generated by Django 5.0.6 on 2024-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invito',
            name='fiscal_code',
        ),
        migrations.AddField(
            model_name='invito',
            name='email',
            field=models.EmailField(default='andrea@prova.it', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invito',
            name='error_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
