# Generated by Django 5.0.6 on 2024-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_invito_fiscal_code_invito_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invito',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('error', 'error')], max_length=10),
        ),
    ]
