# Generated by Django 5.0.6 on 2024-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_invito_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invito',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
