# Generated by Django 5.0.6 on 2024-07-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraccount_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='p_iva',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
