version: "3"

services: 
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_DB: GestioneCentriFitness_CenterHandling
    ports:
      - '5959:5432'
    networks:
      - microservice-network

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5061:5050'
      - '97:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: centerhandling@centerhandling.it
      PGADMIN_DEFAULT_PASSWORD: centerhandling
    networks:
      - microservice-network


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservice-network


  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - microservice-network

  center-handling:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - postgresql
      - kafka
    networks:
      - microservice-network
    
  center-handling-email-consumer:
    build: .
    command: >
      sh -c "
      sleep 10 && python manage.py runEmailConsumer"
    volumes:
      - .:/app
    depends_on:
      - center-handling
      - kafka
    networks:
      - microservice-network

  center-handling-consumer:
    build: .
    command: >
      sh -c "
      sleep 15 && python manage.py runConsumer"
    volumes:
      - .:/app
    depends_on:
      - center-handling
      - kafka
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
